--DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS ratings
(
    id   integer auto_increment,
    name character varying(255) not null,
    constraint rating_pk primary key (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   integer auto_increment,
    name character varying(255) not null,
    constraint genre_pk primary key (id)
);

CREATE TABLE IF NOT EXISTS films
(
    id           bigint generated by default as identity primary key,
    name         character varying(200) not null,
    description  character varying(200),
    release_date date                   not null,
    duration     integer                not null,
    rating_id    integer                not null REFERENCES ratings (id)
);

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  integer REFERENCES films (id),
    genre_id integer REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       INTEGER generated by default as identity primary key,
    email    character varying(255) not null,
    login    character varying(255) not null,
    name     character varying(255) not null,
    birthday date
);

CREATE TABLE IF NOT EXISTS films_likes
(
    film_id integer REFERENCES films (id),
    user_id integer REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   integer REFERENCES users (id),
    friend_id integer REFERENCES users (id),
    status    boolean not null
);