--DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS ratings
(
    id   bigint auto_increment,
    name character varying(255) unique not null,
    constraint rating_pk primary key (id)
);

CREATE TABLE IF NOT EXISTS genres
(
    id   bigint auto_increment,
    name character varying(255) unique not null,
    constraint genre_pk primary key (id)
);

CREATE TABLE IF NOT EXISTS films
(
    id           bigint generated by default as identity primary key,
    name         character varying(200) not null,
    description  character varying(200),
    release_date date                   not null,
    duration     integer                not null,
    rating_id    bigint                not null REFERENCES ratings (id)
);

CREATE TABLE IF NOT EXISTS films_genres
(
    film_id  bigint REFERENCES films (id),
    genre_id bigint REFERENCES genres (id),
    PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS users
(
    id       bigint generated by default as identity primary key,
    email    character varying(255) not null,
    login    character varying(255) not null,
    name     character varying(255) not null,
    birthday date
);

CREATE TABLE IF NOT EXISTS films_likes
(
    film_id bigint REFERENCES films (id),
    user_id bigint REFERENCES users (id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS friends
(
    user_id   bigint REFERENCES users (id),
    friend_id bigint REFERENCES users (id),
    status    boolean not null,
    PRIMARY KEY (user_id, friend_id)
);